version : "3"

services :
  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    restart: on-failure

  frontend:
    image: airways-spa
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: on-failure